#!/bin/bash
python run.py --algorithm IGA --q 284 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 252 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 284 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 278 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 76 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 252 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 155 --l 10 --h 30 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 211 --l 5 --h 16 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 76 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 203 --l 23 --h 69 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 217 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 217 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 287 --l 5 --h 15 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 217 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 289 --l 5 --h 16 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 287 --l 5 --h 15 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 213 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 203 --l 23 --h 69 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 248 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 118 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 73 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 297 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 195 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 197 --l 3 --h 10 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 248 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 277 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 215 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 136 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 276 --l 7 --h 21 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 196 --l 5 --h 15 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 274 --l 7 --h 21 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 116 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 54 --l 9 --h 27 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 149 --l 8 --h 25 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 98 --l 3 --h 10 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 262 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 116 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 126 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 121 --l 8 --h 25 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 159 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 152 --l 5 --h 16 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 161 --l 6 --h 19 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 84 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 40 --l 7 --h 21 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 224 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 66 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 150 --l 8 --h 25 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 162 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 144 --l 9 --h 27 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 245 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 33 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 174 --l 5 --h 15 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 48 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 242 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 140 --l 9 --h 27 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 174 --l 5 --h 15 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 75 --l 5 --h 16 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 185 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 291 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 239 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 82 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 243 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 82 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 168 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 82 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 241 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 65 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 86 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 86 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 240 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 83 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 134 --l 8 --h 25 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 182 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 237 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 235 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 237 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 46 --l 7 --h 21 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 235 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 16 --l 10 --h 30 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 57 --l 9 --h 27 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 57 --l 9 --h 27 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 70 --l 4 --h 12 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 173 --l 7 --h 22 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 23 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 23 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 23 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 23 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 23 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 157 --l 17 --h 51 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 170 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 43 --l 7 --h 21 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 113 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 113 --l 14 --h 43 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 28 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 28 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 28 --l 2 --h 6 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 91 --l 3 --h 9 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 2 --l 10 --h 30 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 29 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
python run.py --algorithm IGA --q 29 --l 15 --h 46 --t 1 --network ./ds/railway/network.dat
