#!/bin/bash
python run.py --algorithm IGA --q 99 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 18 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 28 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 99 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 18 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 28 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 89 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 47 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 89 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 47 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 55 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 55 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 87 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 90 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 80 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 25 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 15 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 104 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 42 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 58 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 101 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 43 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 91 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 43 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 42 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 83 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 95 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 19 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 51 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 15 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 17 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 56 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 85 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 60 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 79 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 58 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 94 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 88 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 63 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 50 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 52 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 82 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 64 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 22 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 38 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 52 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 64 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 22 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 40 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 78 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 48 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 69 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 78 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 53 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 24 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 14 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 81 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 26 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 27 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 27 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 81 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 20 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 37 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 20 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 31 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 92 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 32 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 13 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 10 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 33 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 33 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 10 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 66 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 66 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 11 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 39 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 11 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 65 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 61 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 61 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 73 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 12 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm IGA --q 8 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
