#!/bin/bash
python run.py --algorithm SMA --q 57544 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 110277 --l 4 --h 12 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 49770 --l 4 --h 12 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 1995 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 25981 --l 2 --h 6 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 8949 --l 5 --h 16 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 31849 --l 3 --h 9 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 47309 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 17632 --l 2 --h 6 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 110660 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 47534 --l 2 --h 6 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 11203 --l 2 --h 6 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 217019 --l 2 --h 6 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 17605 --l 2 --h 7 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 156122 --l 4 --h 12 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 45216 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 23934 --l 2 --h 7 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 198512 --l 1 --h 4 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 41762 --l 3 --h 10 --t 1 --network ./ds/amazon/network.dat
python run.py --algorithm SMA --q 43267 --l 12 --h 37 --t 1 --network ./ds/amazon/network.dat