#!/bin/bash
python run.py --algorithm SMA --q 10 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 33 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 21 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 24 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 13 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 24 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 26 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 25 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 27 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 21 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 24 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 15 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 33 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 15 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 25 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 33 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 33 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 26 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 28 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 15 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 26 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 24 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 28 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 22 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 13 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 22 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 22 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 28 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 27 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 26 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 25 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 21 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 15 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 27 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 4 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 32 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 9 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 32 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 14 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 19 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 14 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 19 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 14 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 9 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 9 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 30 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 14 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 31 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 6 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 7 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 17 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 18 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 6 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 17 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 6 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 6 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 31 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 7 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 31 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 6 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 17 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 7 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 31 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 17 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 29 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 29 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 12 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 29 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 29 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 29 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 8 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 8 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 16 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 3 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 1 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 2 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 2 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 2 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 20 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 20 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 0 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 0 --l 8 --h 24 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 23 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
python run.py --algorithm SMA --q 23 --l 9 --h 27 --t 1 --network ./ds/karate/network.dat
