#!/bin/bash
python run.py --algorithm IGA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 61 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 22 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 37 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 55 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 49 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 61 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 55 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 27 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 60 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 56 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 27 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 35 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 10 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 53 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 35 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 53 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 9 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 9 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 17 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 12 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 42 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 12 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 42 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 40 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 20 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 6 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 20 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 52 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 6 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 44 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 13 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 7 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 26 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 43 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 26 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 43 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 36 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 36 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 32 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 23 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 2 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm IGA --q 2 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
