#!/bin/bash
python run.py --algorithm SMA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 61 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 22 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 37 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 55 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 51 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 49 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 61 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 38 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 55 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 27 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 60 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 56 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 27 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 35 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 10 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 53 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 35 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 19 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 53 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 50 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 9 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 24 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 16 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 9 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 17 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 12 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 42 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 12 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 11 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 42 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 30 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 40 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 20 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 6 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 20 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 52 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 29 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 5 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 6 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 25 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 44 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 15 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 3 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 13 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 7 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 26 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 43 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 26 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 43 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 36 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 36 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 32 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 28 --l 10 --h 30 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 23 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 39 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 2 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
python run.py --algorithm SMA --q 2 --l 21 --h 62 --t 1 --network ./ds/dolphin/network.dat
