#!/bin/bash
python run.py --algorithm SMA --q 99 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 18 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 28 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 99 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 18 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 28 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 89 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 47 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 89 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 47 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 55 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 55 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 87 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 90 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 80 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 25 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 15 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 104 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 42 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 58 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 101 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 43 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 91 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 43 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 42 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 35 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 83 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 95 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 19 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 51 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 15 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 17 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 56 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 85 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 60 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 79 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 58 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 94 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 0 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 88 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 63 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 50 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 52 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 82 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 64 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 22 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 38 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 52 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 64 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 22 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 75 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 40 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 78 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 48 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 69 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 78 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 53 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 24 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 14 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 81 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 26 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 27 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 27 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 81 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 20 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 37 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 20 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 31 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 6 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 92 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 32 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 13 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 68 --l 6 --h 19 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 10 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 33 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 33 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 10 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 66 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 66 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 11 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 39 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 11 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 65 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 61 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 61 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 73 --l 21 --h 64 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 12 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
python run.py --algorithm SMA --q 8 --l 24 --h 73 --t 1 --network ./ds/polbooks/network.dat
